# Generated by Django 3.2.7 on 2021-11-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.lecturer'),
        ),
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.schedule'),
        ),
    ]
