# Generated by Django 3.2.7 on 2021-11-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classannouncement',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
