# Generated by Django 3.2.7 on 2021-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_classannouncement_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classannouncement',
            name='time_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='classcontent',
            name='time_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='classcontent',
            name='time_modified',
            field=models.DateTimeField(),
        ),
    ]
