# Generated by Django 3.2.7 on 2021-11-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_classannouncement_time_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcontent',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
