# Generated by Django 3.2.7 on 2021-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_classfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfeedback',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
