# Generated by Django 3.2.7 on 2021-11-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classwork', '0001_initial'),
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.class'),
        ),
    ]
