# Generated by Django 3.2.7 on 2021-11-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Classwork', '0002_test_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.student'),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.test'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='choice_ans',
            field=models.ManyToManyField(blank=True, to='Classwork.MultipleChoiceOption'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.question'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.studenttest'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.test'),
        ),
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.question'),
        ),
    ]
