# Generated by Django 3.2.7 on 2021-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
