# Generated by Django 3.2.5 on 2021-11-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0004_alter_studenttest_is_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
