# Generated by Django 3.2.7 on 2021-12-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0005_test_test_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_file',
            new_name='attached_file',
        ),
    ]
