# Generated by Django 3.2.7 on 2021-12-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0006_rename_test_file_test_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
