# Generated by Django 3.2.7 on 2021-12-02 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0007_test_is_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='tests/'),
        ),
        migrations.CreateModel(
            name='StudentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/')),
                ('file_description', models.TextField(blank=True, null=True)),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classwork.studenttest')),
            ],
        ),
    ]
