# Generated by Django 3.2.7 on 2021-12-02 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0008_auto_20211202_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentupload',
            old_name='file',
            new_name='attached_file',
        ),
    ]
