# Generated by Django 3.2.7 on 2021-12-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0009_rename_file_studentupload_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentupload',
            name='student_test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Classwork.studenttest'),
        ),
    ]
