# Generated by Django 3.2.7 on 2021-12-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classwork', '0005_test_time_modified'),
        ('Classwork', '0011_rename_student_test_studentupload_studenttest'),
    ]

    operations = [
    ]
